OS-8319 lx centos family resolver logic should match ubuntu
joyent/illumos-joyent pull request #376
Opened 2021-09-29 19:25 UTC by papertigers

2021-09-29 19:34 UTC, bahamat requested changes
Will also need to update copyright. `make check` should complain about that.

2021-09-29 19:34 UTC, bahamat commented on usr/src/lib/brand/lx/zone/lx_boot_zone_redhat.ksh
> +resolvers=`zone_attr resolvers`
Prefer `$()`

2021-09-29 19:34 UTC, bahamat commented on usr/src/lib/brand/lx/zone/lx_boot_zone_redhat.ksh
> +    domain=`zone_attr dns-domain`
Prefer `$()`

2021-09-29 19:39 UTC, danmcd commented
Needs testing notes on OS-8319 ticket.

2021-09-29 19:40 UTC, danmcd reviewed
One other question... will this break older Centos?  Do we care if it does?

2021-09-29 19:48 UTC, danmcd approved these changes
Comment about older Centos addressed by Brian on Slack.  Don't forget test notes!

2021-09-29 19:58 UTC, bahamat approved these changes

2021-09-29 20:01 UTC, merged

2021-09-30 05:48 UTC, sjorge commented on usr/src/lib/brand/lx/zone/lx_boot_zone_redhat.ksh
> +# Populate resolv.conf setup files IFF we have resolvers information.
IFF?

2021-09-30 15:44 UTC, danmcd commented
"IFF" == shorthand for "if and only if".

2021-09-30 17:35 UTC, sjorge commented
> "IFF" == shorthand for "if and only if".

I see, never seen that before! TIL

2021-09-30 17:37 UTC, danmcd commented
Yeah, college/uni-level math classes and/or theoretical Computer Science drilled that into my head.  It also has formal logic implications:  a  -->  b   (If A then B), a <-- b, (A only if B), and a <--> b (A if and only if B, aka A IFF B).